name: Build Docker Image risk_report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag risk_report
